name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 或你当前的默认分支名称，例如 master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          - name: Install dependencies
          run: npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite 默认输出打包物目录
          branch: gh-pages # 部署到自动化分支 gh-pages
